WebApplication39/WebApplication39/Controllers/DepoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebApplication39.Interfaces.Manager;
using WebApplication39.Manager;
using WebApplication39.Models;

namespace WebApplication39.Controllers
{
    public class DepoController : Controller
    {
        private IDepoManager _depoManager = new DepoManager();
        public IActionResult Index()
        {
            var depos = _depoManager.GetAll();
            return View(depos);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Depo depo)
        {
            depo.Id = Guid.NewGuid().ToString();
            bool isSaved = _depoManager.Add(depo);
            string mgs = "";
            if (!ModelState.IsValid)
            {
                return View("Create");
            }
            if (isSaved)
            {
                return RedirectToAction("Index");
            }
            else
            {
                mgs = "Saved failed";
            }
            ViewBag.Mgs = mgs;
            return View();

        }
        public ActionResult Edit(string id)
        {

            var depo = _depoManager.GetById(id);
            if (depo == null)
            {
                return NotFound();
            }
            return View(depo);

        }


        [HttpPost]
        public ActionResult Edit(Depo depo)
        {
            bool isUpdated = _depoManager.Update(depo.Id, depo);
            if (isUpdated)
            {
                return RedirectToAction("Index");
            }

            return View(depo);

        }
        public ActionResult Details(string id)
        {

            var depo = _depoManager.GetById(id);
            if (depo == null)
            {
                return NotFound();

            }
            return View(depo);

         }
        public ActionResult Delete(string id)
        {
            var depo = _depoManager.GetById(id);
            if (depo == null)
            {
                return NotFound();

            }
            return View(depo); 
        }
        [HttpPost]
        public ActionResult Delete(Depo depo)
        {

            bool isDelete = _depoManager.Delete(depo.Id);
            if (isDelete)
            {
                return RedirectToAction("Index");
            }
            ViewBag.Mgs = "Depo delete failed";
            return View(depo);
        }
    }
}

WebApplication39/WebApplication39/Controllers/GirisController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebApplication39.Database;
using WebApplication39.Models;

namespace WebApplication39.Controllers
{
    public class GirisController : Controller
    {
        
        
        public IActionResult Index()
        {
            return View();
        }


        

		


	}
}

WebApplication39/WebApplication39/Controllers/IsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebApplication39.Interfaces.Manager;
using WebApplication39.Manager;
using WebApplication39.Models;

namespace WebApplication39.Controllers
{
    public class IsController : Controller
    {
        private IIsManager _isManager = new IsManager();
        public IActionResult Index()
        {
            var iss = _isManager.GetAll();
            return View(iss);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Is iss)
        {
            iss.Id = Guid.NewGuid().ToString();
            bool isSaved = _isManager.Add(iss);
            string mgs = "";
            if (isSaved)
            {
                return RedirectToAction("Index");
            }
            else
            {
                mgs = "Saved failed";
            }
            if (!ModelState.IsValid)
            {
                return View("Create");
            }
            ViewBag.Mgs = mgs;
            return View();

        }
        public ActionResult Edit(string id)
        {

            var iss = _isManager.GetById(id);
            if (iss == null)
            {
                return NotFound();
            }
            return View(iss);

        }


        [HttpPost]
        public ActionResult Edit(Is iss)
        {
            bool isUpdated = _isManager.Update(iss.Id, iss);
            if (isUpdated)
            {
                return RedirectToAction("Index");
            }

            return View(iss);

        }
        public ActionResult Details(string id)
        {

            var iss = _isManager.GetById(id);
            if (iss == null)
            {
                return NotFound();

            }
            return View(iss);

        }
        public ActionResult Delete(string id)
        {
            var iss = _isManager.GetById(id);
            if (iss == null)
            {
                return NotFound();

            }
            return View(iss);
        }
        [HttpPost]
        public ActionResult Delete(Is iss)
        {

            bool isDelete = _isManager.Delete(iss.Id);
            if (isDelete)
            {
                return RedirectToAction("Index");
            }
            ViewBag.Mgs = "Depo delete failed";
            return View(iss);
        }
    }
}

WebApplication39/WebApplication39/Controllers/MaasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication39.Interfaces.Manager;
using WebApplication39.Manager;
using WebApplication39.Models;

namespace WebApplication39.Controllers
{
    public class MaasController : Controller
    {
        IMaasManager _maasManager = new MaasManager();
        public IActionResult Index()
        {
            var maasies = _maasManager.GetAll();
            return View(maasies);
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(Maas maas)
        {
            maas.Id = Guid.NewGuid().ToString();
            bool isSaved = _maasManager.Add(maas);
            string mgs = "";
            if (isSaved)
            {
                mgs = "Maas kaydedildi";
            }
            else
            {
                mgs = "Maas save hatasi";
            }
            ViewBag.Mgs = mgs;
            return View();
        }

    }
}

WebApplication39/WebApplication39/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ANASAYFA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ANASAYFA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calisan" asp-action="Index">ÇALIŞAN</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Maas" asp-action="Index">MAAŞ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Depo" asp-action="Index">DEPO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hakkımızda" asp-action="Index">HAKKIMIZDA</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Is" asp-action="Index">İŞLER</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">LOGIN</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Musteri" asp-action="Index">MÜŞTERİ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Raporlar" asp-action="Index">RAPORLAR</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Giris" asp-action="Index">ÇIKIŞ</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>